build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.15
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi

tests:
- as: unit
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.9"
  commands: make test
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: freeipa
  repo: freeipa-operator
